# Generated by Django 2.0.7 on 2018-10-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDatas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pill',
            old_name='qrcode',
            new_name='QR_AI01',
        ),
    ]
